### ISSUE TITLE
There is no any section for player1 and player2 turn

### ISSUE THREAD

**Issue by md-jishan-ansari** [subhamdas461/simple-TicTacToe#5]

**Comment by md-jishan-ansari** [comment]
Please assign me I can make a section for player turns

**Comment by subhamdas461** [comment]
> 
> 
> Please assign me I can make a section for player turns

Yeah sure @md-jishan-ansari .👍

**Comment by SujeetYT** [comment]
I want to try this please assign it to me

**Comment by subhamdas461** [comment]
> I want to try this please assign it to me I'll make player's turn section using javascript

This part is done @SujeetYT . If you have any suggestion, make your changes👍

**Comment by SujeetYT** [comment]
I guess instead of prompt for winner it should be a celebration banner at place of player's turn,
I'm going to make this change in separate branch please accept my PR if you like it
