### ISSUE TITLE
disable the click for remaining boxes after declaration of result

### ISSUE THREAD

**Issue by sujeetcodes** [subhamdas461/simple-TicTacToe#9]
After the result is declared the user must not able to click remaining buttons

**Comment by subhamdas461** [comment]
> 
> 
> > After results are declared, an overlay is shown. So I think it's fine.
> 
> yeah! someone has made this so I cannot do this or it will show conflicts

Yeah someone did that. So if you have any other suggestions or any issues, feel free to make the changes.👍
